ignoredBuiltDependencies:
  - '@compodoc/compodoc'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - cypress
  - esbuild
  - lmdb
  - msgpackr-extract
onlyBuiltDependencies:
  - nx
  - unrs-resolver
